version: '3'

services:
  mysqldb:
    image: mysql:8-oracle

    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fullstack


  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/fullstack

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
