name: Build and Deploy to Local



on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up JDK for backend build
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Spring Boot jar
      working-directory: ./backend
      run: ./mvnw clean package -DskipTests


    - name: Deploy to local
      run: |
          cd /home/quanchip/aws-cicd-test-app1/React-Springboot-App
          docker-compose down
          docker-compose up -d --build
